### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by CodeS-A** [MasterDevX/Termux-Java#16]
This script will install Java in Termux.
Libraries compiled by Hax4us, script written by Hax4us and MasterDevX.

[*] Downloading JDK-8 (~70Mb) for arm...
[*] Moving JDK to system...
[*] Extracting JDK...
[*] Moving Java wrapper scripts to bin...
[*] Cleaning up temporary files...

Java was successfully installed!

┌─[u0_a189@localhost]─[]
└──╼ $java
Segmentation fault
┌─ [✗]─[u0_a189@localhost]─[]
└──╼ $javac
Segmentation fault
┌─ [✗]─[u0_a189@localhost]─[]
└──╼ $jar
Segmentation fault
┌─ [✗]─[u0_a189@localhost]─[]
└──╼ $

**Comment by CupCakefanuwu** [comment]
E

**Comment by Lumino2003** [comment]
Aun no los has solucionado?

**Comment by Ben1701A** [comment]
Also getting this issue. Segfaults within 100ms of return key. *sigh*

**Comment by themeliskalomoiros** [comment]
So sad to come near the fountain and unable to drink water.

**Comment by azmaat1** [comment]
🤣

في الاثنين، ٣٠ نوفمبر ٢٠٢٠ ١:٢٠ ص Themelis Kalomoiros <
notifications@github.com> كتب:

**Comment by MasterDevX** [comment]
Closing as duplicate of https://github.com/MasterDevX/Termux-Java/issues/14

**Comment by TadavomnisT** [comment]
I had the same condition, fixed it by following instructions:

`$ pkg install wget -y `
` $ wget https://archive.org/download/openjdk-9-jre-headless_9.2017.8.20-1_x86_64/openjdk-9-jdk-headless_9.2017.8.20-1_arm.deb `
` $ wget https://archive.org/download/openjdk-9-jre-headless_9.2017.8.20-1_x86_64/openjdk-9-jre-headless_9.2017.8.20-1_arm.deb`
` $ apt-get install -y ./openjdk-9-jre-headless_9.2017.8.20-1_arm.deb`
` $ apt-get install -y ./openjdk-9-jdk-headless_9.2017.8.20-1_arm.deb ` 

IDK for sure , but looks like there was some sort of problem with jdk/jre binary installation and some data happened to be missing.
Hope it helps
