### ISSUE TITLE
Bad system call

### ISSUE THREAD

**Issue by lusantisuper** [MasterDevX/Termux-Java#17]
![Screenshot_20200319-134311](https://user-images.githubusercontent.com/24521882/77091774-bf88d900-69e7-11ea-90e3-66c41fe567f6.jpg)
When I try to run Java and javac, that error appears, but when I try whit proot it works fine.

**Comment by MasterDevX** [comment]
Running Java with PRoot is the only solution for now :/
Because of workaround for this was already found in https://github.com/MasterDevX/Termux-Java/issues/3 I'm closing this.
