### ISSUE TITLE
Java command returns "Killed"

### ISSUE THREAD

**Issue by hessam94** [MasterDevX/Termux-Java#19]
Hello,
I went through the steps. after installing java it seems everything is installed successfully without any error. but after i run java command or java -version, it returns me "Killed". no idea why. 

Also i want to run some commands like update "sudo yum/apt-get update -y" but these two command says "command not found". Please help me

Thanks

**Comment by GuzioMG** [comment]
When it comes to your second problem:
- use `pkg install <package name>`, ...`upgade`, ...`remove (name)` or ...`search (query)`. No need for `pkg update`, since updates are automatic.
- `sudo` does not exist here (**maybe** unless you rooted your device, but I didn't root, so I don't know). If you really want to run a command as `sudo`, use `proot -0` instead.
- Although you should use `pkg`, `apt` exists and does not require root/`sudo` permission here.
- `yum` does not exist. This terminal is (very slightly) Ubuntu-like.

**Comment by GuzioMG** [comment]
Also, the `killed` problem is already traced on #7.

**Comment by hessam94** [comment]
> When it comes to your second problem:
> 
> * use `pkg install <package name>`, ...`upgade`, ...`remove (name)` or ...`search (query)`. No need for `pkg update`, since updates are automatic. Do **NOT** run this with root/`sudo` permissions.
> * `sudo` does not exist here (**maybe** unless you rooted your device, but I didn't root, so I don't know). If you really want to run a command as `sudo`, use `proot -0` instead, although it's not a real root, so some very-root apps can crash, if you use that.
> * Although you should use `pkg`, `apt` exists and does not require root/`sudo` permissions here.
> * `yum` does not exist. This terminal is (very slightly) Ubuntu-like.

Thanks for your response. I need to install some packages form linux, but it seems there are only a few limited packages are provided in your https://dl.bintray.com/grimler/ webpage. is that right? Hoe can i install other packages? do i need another terminal emulator? thanks

**Comment by GuzioMG** [comment]
> it seems there are only a few limited packages are provided in your https://dl.bintray.com/grimler/ webpage. is that right?

On https://dl.bintray.com/grimler/ you have additional repositories (which are also installed as regular packages, btw). If you want a list of all packages you can install, either type `pkg list-all` or _(if you really want a link for some reason)_ go to https://github.com/termux/termux-packages/tree/master/packages instead.

> Thanks for your response. I need to install some packages form Linux, but it seems there are only a few limited packages are provided in your https://dl.bintray.com/grimler/ webpage. is that right? Hoe can I install other packages? do I need another terminal emulator? thanks

If your package is not included in the main repo, you can try installing those from https://dl.bintray.com/grimler/ as is they were regular packages (i. e. `pkg install <package (in this case repository) name>`). After that, `pkg list-all` will include packages from added repos, too.

If you _still_ can't find your desired package, try installing [its-pointless](https://github.com/its-pointless/gcc_termux) repo by running

```
curl -LO https://its-pointless.github.io/setup-pointless-repo.sh

bash setup-pointless-repo.sh
```

If it does not work, your last resort is using `dpkg -i ./<package name>.deb` to install a DEB package, **but make sure you've downloaded a package for your CPU architecture. Most packages you find online are going to be for x86 architecture. Make sure, you're downloading for YOUR REVISION of ARM architecture**.

**Comment by hessam94** [comment]
thank you very much for your kind help. Actually i am installing docker on android. I got docker binaries and extract/install it well. docker --version work correctly. But any other docker command does not work. anyway. after lots of search it seems these packages are not installed and I don't know how to get it. I could get docker binaries via adb shell and root. 
_**1- systemctl   2-systemd**_ 
after "systemctl status docker" it shows me "**_systemctl not found_**" 
1- how can i install systemctl. i searched but couldnt solved it on tremux and android. even systemd not found. it seems i need it to start docker deamon
