### ISSUE TITLE
Bad System Call

### ISSUE THREAD

**Issue by 7Ragnarok7** [MasterDevX/Termux-Java#23]
Shows Bad system call after installing and trying to run java --version or java or javac

**Comment by DeicPro** [comment]
Same

**Comment by maleko48** [comment]
same here on LG V60 non-rooted stock phone w/Android 10

**Comment by sencrash** [comment]
Duplicate of #3

**Comment by 7Ragnarok7** [comment]
Hello @everyone This issue has already been solved.
You have to use proot -0 to get root permission and then call java or javac and it should work.

I'm closing this thread.

**Comment by 7Ragnarok7** [comment]
> Hello @everyone This issue has already been solved.
> You have to use proot -0 to get root permission and then call java or javac and it should work.
> 
> I'm closing this thread.

**Comment by 7Ragnarok7** [comment]
Hello @everyone This issue has already been solved.
You have to use proot -0 to get root permission and then call java or javac and it should work.

Please close this thread @MasterDevX
Thank You @sencrash .
