### ISSUE TITLE
Java Command Not Found

### ISSUE THREAD

**Issue by HiddenPirates** [MasterDevX/Termux-Java#26]
After getting success massage of installation..
When I run java command in termux. I got command not found error.
![Screenshot_2020-07-04-14-29-47-54_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/59209516/86509091-171a4b80-be03-11ea-84ca-35e46880bba5.jpg)

**Comment by 7Ragnarok7** [comment]
I think you have to include the bin folder in your path in environment variables.

**Comment by tathastu871** [comment]
export PATH="$PREFIX/bin:$PATH"
proot -0 java --version

**Comment by MasterDevX** [comment]
Suggestions from @7Ragnarok7 and @tathastu871 should work.
