### ISSUE TITLE
java killed

### ISSUE THREAD

**Issue by cctyl** [MasterDevX/Termux-Java#29]
when i installed jdk ,i try to excute 'java -version',but it show 'killed'. 
`Same` with other commands

![Snipaste_2020-09-10_21-05-15](https://user-images.githubusercontent.com/34262992/92732952-b2064780-f3a9-11ea-9cee-f55dc71c34cd.png)

**Comment by cctyl** [comment]
![Snipaste_2020-09-10_21-08-25](https://user-images.githubusercontent.com/34262992/92733047-cc402580-f3a9-11ea-9b1e-280615b12445.png)

**Comment by Hxyspace** [comment]
same
![image](https://user-images.githubusercontent.com/43908359/94430410-73a0c300-01c6-11eb-80a0-e2cc9c9a04cf.png)

**Comment by Hxyspace** [comment]
This is solved using this method https://github.com/MasterDevX/Termux-Java/issues/7#issuecomment-653526860

**Comment by cctyl** [comment]
后来直接装了Ubuntu，可以直接装jdk了




------------------ Original ------------------
