### ISSUE TITLE
[Android O / P] Bad system call

### ISSUE THREAD

**Issue by frhnfrq** [MasterDevX/Termux-Java#3]
Hi,
Getting this. Can you help?
![Screenshot_20190606-142010](https://user-images.githubusercontent.com/13793708/59017725-101eb380-8866-11e9-9bd7-11b05373c065.jpg)

**Comment by MasterDevX** [comment]
What Android version are you running?

**Comment by frhnfrq** [comment]
Android 9. OnePlus 6 (A6000)

**Comment by MasterDevX** [comment]
Yeah, there are some problems like this with Android Pie.

**Comment by frhnfrq** [comment]
Oh! Is there any way to fix it?

**Comment by MasterDevX** [comment]
Not sure. If you have PC you can try to get LogCat using ADB ad upload it here.

**Comment by Techno-Developer** [comment]
I have the same problem with Android 8.0.0, i will upload logcat if it can hell.

**Comment by Techno-Developer** [comment]
I have the same problem with Android 8.0.0 and i can upload logcat if useful.

**Comment by MasterDevX** [comment]
> I have the same problem with Android 8.0.0 and i can upload logcat if useful.

Yep, it will be good.
Looks like Android 8+ problem..

**Comment by Techno-Developer** [comment]
> > I have the same problem with Android 8.0.0 and i can upload logcat if useful.
> 
> Yep, it will be good.
> Looks like Android 8+ problem..

I've read all the logcat of termux PID while sending `javac` command but i haven't found nothing useful.

**Comment by ReekyStive** [comment]
Android Pie, Bad system call, too.

**Comment by Mantisimo** [comment]
Getting the same android version 9

**Comment by GoogleSites** [comment]
Same here. Galaxy A20, Android 9

**Comment by SudhitChauhan** [comment]
Same problem ! Redmi 5A, Android 8.1

**Comment by TheusKhan** [comment]
Last month I was able to use normally on Android 9, so I changed my ROM and now I get this error.  The new ROM is Android Pie too.

**Comment by MasterDevX** [comment]
@ReekyStive Have you changed from stock to custom, or...?

**Comment by MasterDevX** [comment]
@TheusKhan Have you changed from stock to custom, or...?

**Comment by TheusKhan** [comment]
I changed from custom ROM to another custom ROM. My device is Redmi 4X, aka Santoni. 
Was working fine on POSP with 4.9 linux kernel. 
But now doesn't work on Havoc OS with 3.18 Linux kernel. Both are Android Pie AOSP ROMs.

**Comment by phil2sat** [comment]
Install tsu thenn as root it works

**Comment by Flamexxx** [comment]
the same probleme here

**Comment by nalexcastaneda** [comment]
Same problem on Android 9  3.18 Kernel

**Comment by MasterDevX** [comment]
Lol, so many people facing this and still no solution. Marking as "won't fix" for now..

**Comment by Dzuchun** [comment]
same problem

**Comment by njchensl** [comment]
Same problem for me also, using android pie with lineage os 16

**Comment by kcubeterm** [comment]
Hey all before running java run `proot -0 `
It will work

**Comment by Dzuchun** [comment]
> Hey all before running java run `proot -0 `
> It will work

@kcubeterm 
nope, typing "java" in any case causes bad system call:
![20191101_064232](https://user-images.githubusercontent.com/46713596/68002704-dade8c00-fc72-11e9-880f-884f0769031d.jpg)
it even won't display jar argument syntax as shown above.

**Comment by kcubeterm** [comment]
See in android 9 it works
![Screenshot_2019-11-01-11-42-37-866_com termux](https://user-images.githubusercontent.com/50498359/68005892-d038ec80-fc9c-11e9-8603-a482c6ce4257.png)
First ,when I run just `java`
It didn't run
But when I execute `proot -0 ` here "0"is zero okkk

**Comment by Dzuchun** [comment]
For android 9 works, confirm.
Thanks everyone!

**Comment by nalexcastaneda** [comment]
It works with `proot -0` it was as simple as that 😅

**Comment by Techno-Developer** [comment]
@kcubeterm Thanks a lot, running `proot -0` before calling Java, fixed the issue! I think that a slight modification to the installation script can make this automatic @MasterDevX

**Comment by MasterDevX** [comment]
Big thanks to the @kcubeterm for the solution, I think we can finally close this :+1:

**Comment by MasterDevX** [comment]
> I think that a slight modification to the installation script can make this automatic

Don't know if it is a good idea, cuz some users who don't want to be in a PRoot environment will be forced to use it.

**Comment by Frankystar777** [comment]
Damn I got an error message with command : proof -0

**Comment by GuzioMG** [comment]
Reports success from Android 10 on Samsung Galaxy S10e!

**Comment by aldin99** [comment]
> See in android 9 it works
> ![Screenshot_2019-11-01-11-42-37-866_com termux](https://user-images.githubusercontent.com/50498359/68005892-d038ec80-fc9c-11e9-8603-a482c6ce4257.png)
> First ,when I run just `java`
> It didn't run
> But when I execute `proot -0 ` here "0"is zero okkk
> Then I execute keytool it's worked

Thank you its works

**Comment by bucketsort** [comment]
If you run javac in termux using strace you'll see what's wrong.

According to this link: https://github.com/termux/termux-packages/issues/420

the error is because you compile against a libc that doesn't know about the restrictions on syscalls in newer Android versions.

In our case this is the syscall (strace):

set_robust_list(0x74b24e50e0, 24)       = 501207683296
--- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x74b249c790, si_syscall=__NR_set_robust_list, si_arch=AUDIT_ARCH_AARCH64} ---                                             +++ killed by SIGSYS +++
Bad system call

**Comment by TITANHACKY** [comment]
We can't use java without prior -0 ?

**Comment by VergeDX** [comment]
Yes, exec tsu and java works.

**Comment by TITANHACKY** [comment]
> Yes, exec tsu and java works.

Yes when we use tsu it will work but most of the users only have unrooted android including me

**Comment by sabaribeep** [comment]
> Damn I got an error message with command : proot -0

First install proot boss :-)

**Comment by Mina93-min** [comment]
Write in termux   `termux-chroot`

**Comment by Enforc3rr** [comment]
XDD incase anyone thinks -proot 0 is tiresome to type everytime , i suggest you to use sudo instead

**Comment by suhui8** [comment]
like this : pkg install proot
![1](https://user-images.githubusercontent.com/35110833/104849132-1ec6bb00-5923-11eb-930d-ff98cf7c8bff.png)
![2](https://user-images.githubusercontent.com/35110833/104849137-225a4200-5923-11eb-969d-29339657453b.png)

**Comment by suhui8** [comment]
![3](https://user-images.githubusercontent.com/35110833/104849566-4c146880-5925-11eb-8ca1-3aef58d41596.png)

If you are running SpringBoot, may be specify a tmp folder,
java -Djava.io.tmpdir=/data/data/com.termux/files/home/tmpdir jar xxxxyourJava.jar

**Comment by kcubeterm** [comment]
@DaiMengMei try under termux-chroot

**Comment by ghost** [comment]
![Screenshot_20210510-010247_Termux](https://user-images.githubusercontent.com/38570195/117608162-818acf00-b12b-11eb-9063-70e333365575.jpg)
Not work
![Screenshot_20210510-010504_Termux](https://user-images.githubusercontent.com/38570195/117608316-dcbcc180-b12b-11eb-89c8-4e67c383a004.jpg)

**Comment by ghost** [comment]
install proot
launch with fake root

**Comment by pavan3b8** [comment]
> > I think that a slight modification to the installation script can make this automatic
> 
> Don't know if it is a good idea, cuz some users who don't want to be in a PRoot environment will be forced to use it.

How to remove proot

**Comment by GuzioMG** [comment]
> > > I think that a slight modification to the installation script can make this automatic
> > 
> > Don't know if it is a good idea, cuz some users who don't want to be in a PRoot environment will be forced to use it.
> 
> How to remove proot

WDYM "remove"? Like... Uninstall the package? Just like any other package - `pkg remove proot` or `pkg uninstall proot` (I actually don't remember which one was it).
