### ISSUE TITLE
Bad system call

### ISSUE THREAD

**Issue by Nincodedo** [MasterDevX/Termux-Java#31]
After running the install and trying to run java -version, I only get "Bad system call" as a return.

![Screenshot_20200924-135751](https://user-images.githubusercontent.com/436953/94187790-19260080-fe6e-11ea-8a16-409a0cdbea67.png)

I'm running Android 11 on a Pixel 3a, no root.

**Comment by Sanchit143** [comment]
I'm facing the same issue but Android 10 on OnePlus 8 Pro

**Comment by MrF0o** [comment]
try running
```proot java -version```

**Comment by Sanchit143** [comment]
That actually worked! Thanks!
Could you please explain what was wrong and what did proot to do help it?

**Comment by MrF0o** [comment]
actually i don't know, i tried it and worked :)

**Comment by Sanchit143** [comment]
Okay, thanks for helping!

**Comment by Nincodedo** [comment]
Worked for me too. Thanks!
