### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by 75-hello-world** [MasterDevX/Termux-Java#34]
I entered java -version into a clean install Termux I get this error:

"Bad System Call"

**Comment by josephworks** [comment]
Same here, I am using AArch64.

**Comment by anomalou** [comment]
Same. Using aarch64 architecture

**Comment by SaulGoodman1337** [comment]
Same here...

**Comment by HoseanRC** [comment]
same here :(
i have aarch64

**Comment by 32Vache** [comment]
same

**Comment by MasterDevX** [comment]
Closing as duplicate, check https://github.com/MasterDevX/Termux-Java/issues/3 for solution.
