### ISSUE TITLE
Java not installing

### ISSUE THREAD

**Issue by OmrAmer** [MasterDevX/Termux-Java#4]
When I type 
wget https://raw.githubusercontent.com/MasterDevX/java/master/installjava && bash installjava

Then 

Java 

This happens:

This script will install Java in Termux.
Libraries compiled by Hax4us, script written by Hax4us and MasterDevX.

[*] Downloading JDK-8 (~70Mb) for arm...
[*] Moving JDK to system...
mv: can't rename 'jdk8_arm.tar.gz': No such file or directory
[*] Extracting JDK...
tar: can't open 'jdk8_arm.tar.gz': No such file or directory
[*] Moving Java wrapper scripts to bin...
mv: can't rename 'bin/*': No such file or directory
[*] Cleaning up temporary files...

Java was successfully installed!

$ java
No command 'java' found, did you mean:
 Command 'cava' from package 'cava'
$

 please help me

**Comment by MasterDevX** [comment]
Okay, the first error comes up when downloading tarball.
Try to open 'installjava' script using nano or any other editor you want and remove '-q' from line 30, then save it, run, and send a screenshot, so we can find out where wget fails.

Hovewer, the error might me just caused because of wget was not properly installed, so before doing all the things I described above, try to simply uninstall wget by running 'pkg uninstall wget', then sync repositories using 'apt update' and reinstall wget once again - 'pkg install wget'.

**Comment by OmrAmer** [comment]
I did nano installjava but I get only black screen there is no something written

**Comment by OmrAmer** [comment]
Hello? Can you help me please??

**Comment by OmrAmer** [comment]
Can I installnit manually ? And how??

**Comment by OmrAmer** [comment]
![Uploading Screenshot_٢٠١٩٠٦١٠-٢٢١٤٣٢.jpg…]()
  
sir I did what u said and removed -q now this is the screenshot

**Comment by OmrAmer** [comment]
This is what appears to me :

nano installjava
$ bash installjava

This script will install Java in Termux.
Libraries compiled by Hax4us, script written by Hax4us and MasterDevX.

[*] Downloading JDK-8 (~70Mb) for arm...
--2019-06-10 22:14:07--  https://github.com/Hax4us/java/releases/download/v8/jdk8_arm.tar.gz
Resolving github.com... 140.82.118.4
Connecting to github.com|140.82.118.4|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-06-10 22:14:08 ERROR 404: Not Found.

[*] Moving JDK to system...
mv: cannot stat 'jdk8_arm.tar.gz': No such file or directory
[*] Extracting JDK...
tar: jdk8_arm.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
[*] Moving Java wrapper scripts to bin...
mv: cannot stat 'bin/*': No such file or directory
[*] Cleaning up temporary files...

Java was successfully installed!

$

**Comment by MasterDevX** [comment]
Hmm, looks like download URL changed a little bit, I'll try to fix it now.
P.S. Sorry for late reply, I was busy these days, so I was away from GitHub..

**Comment by MasterDevX** [comment]
Just pushed two new commits, which should fix the issue. Try installing now.

**Comment by Biangkerok32** [comment]
I think need new comit, url https://github.com/Hax4us/java/releases/download/v8/jdk8_arm.tar.gz is not found

real path is https://github.com/Hax4us/java/releases/download/v8-151/jdk8_arm.tar.gz

i hope,you can fix "installjava"

Cheers,

**Comment by MasterDevX** [comment]
Already fixed, try it out.

**Comment by OmrAmer** [comment]
Ok the problem is solved but this new problem apears to me:

This script will install Java in Termux.
Libraries compiled by Hax4us, script written by Hax4us and MasterDevX.

[*] Downloading JDK-8 (~70Mb) for arm...
[*] Moving JDK to system...
[*] Extracting JDK...
[*] Moving Java wrapper scripts to bin...
[*] Cleaning up temporary files...

Java was successfully installed!

$ java
Segmentation fault
$

Please don't be late in the answer and thank you.

**Comment by OmrAmer** [comment]
My phone is Galaxy J7 prime 2 , and Android : 7.1.1

And my phone is rooted

**Comment by MasterDevX** [comment]
Redirecting to https://github.com/MasterDevX/Termux-Java/issues/2
