### ISSUE TITLE
Fallo de semengtacion 

### ISSUE THREAD

**Issue by JesusChapman** [MasterDevX/Termux-Java#41]
Amigo, al ejecutarlo no me sirve, sabes por que?, trate de usar proot y tampoco funcionó

**Comment by nexxii04** [comment]
Exactamente qué no te sirve? El coamando o el script de instalación

**Comment by JesusChapman** [comment]
> ¿Exactamente qué no te sirve? El coamando o el script de instalacion

Ya no me es necesario, no funcionaba debido a incompatibilidades con dispositivos de 32 bits.

Igual termux ya empaqueto openjdk en sus repositorios y se puede instalar con `pkg install openjdk-17`
