### ISSUE TITLE
Bad system call

### ISSUE THREAD

**Issue by Sl-Sanda-Ru** [MasterDevX/Termux-Java#61]
![Screenshot_2021-09-11-15-18-11-152_com termux](https://user-images.githubusercontent.com/68476573/132943865-0a843975-1b3b-4933-8a89-911d60118d81.jpg)

My CPU architecture is aarch64
Anyone got a fix for this?

**Comment by cinexsoft** [comment]
Install and then try this

https://github.com/Hax4us/java/issues/7#issuecomment-568185990
You'll need to do this every time.

**EDIT**: A better alternative is to use `proot java`.
You can alias this or add `proot` in the `/bin/java` script.
