### ISSUE TITLE
Proccess killed

### ISSUE THREAD

**Issue by JeelsBoobz** [MasterDevX/Termux-Java#7]
What happend? @MasterDevX [
![Screenshot_Termux_20190614-203401](https://user-images.githubusercontent.com/38210868/59513000-19ea8b80-8ee4-11e9-98eb-1508637e4ce4.png)
](url)

**Comment by MasterDevX** [comment]
Currently I have no idea what causes this..

**Comment by JeelsBoobz** [comment]
Ok thanks

**Comment by MasterDevX** [comment]
Try to run Java in Bash environment, not in Zsh.

**Comment by BomberX02** [comment]
I think it has someting to do with LineageOS.
I get the same error on my Samsung i9100 with LineageOS, and on my huawei y550 with LineageOS as well. From the looks of it @JeelsBoobz runs LineageOS too, since he has android 9. 
I would love to test this, but I can't find any android 5+ roms that aren't based on lineage/cm for these devices.
@JeelsBoobz Could you try running java on a stock rom to see if that works?

**Comment by MasterDevX** [comment]
@BomberX02 I use Resurrection Remix, which is a fork of Lineage and I don't have this problem. If it is Lineage related issue then it must be guys from RR have fixed something in their ROM. Maybe I'll flash Lineage too and check Java there.

**Comment by JeelsBoobz** [comment]
May be this issue only with chipset samsung device

**Comment by JeelsBoobz** [comment]
Maybe 😂

**Comment by JeelsBoobz** [comment]
Tested with another device Redmi Note 4 SD with stock MIUI arm64
Tested with Galaxy S5 ROM LineageOS arm, i have problem
![Screenshot_2019-07-14-10-54-27-214_com termux](https://user-images.githubusercontent.com/38210868/61179119-39c9b800-a626-11e9-8111-eaf4f1a61ffc.png)

**Comment by JeelsBoobz** [comment]
Ok, maybe this bug for armv7l only..
Because, tested with samsung device stockrom armv7l proccess killed 😪
I hope for arm can fixed 🤗

**Comment by PranshuTG** [comment]
Yeah this happens to me too now I can't run the bash command
I was trying to run nukkit on my
Gt 15882

**Comment by KiberDoktor** [comment]
I confirm, on my Realme 6 Pro there is the same problem.  
When you try to start the process, it is killed.

![Screenshot_2020-06-23-11-58-52-98_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/45209187/85359499-f91e3280-b548-11ea-9029-fd789244a95b.jpg)

**Comment by hyperstown** [comment]
On Xperia Z3 Compact same error. Stock ROM.
![image](https://user-images.githubusercontent.com/64496017/85932641-14cd6400-b8ce-11ea-9538-4a6e52053991.png)

**Comment by foxwill-wwei** [comment]
if you have root permission , it may work.

`su`
`export PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:$PATH`
`export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib`

then I tested minecraft:
![image](https://user-images.githubusercontent.com/58242212/86469510-226e6800-bd6c-11ea-9cb6-c1403ebeb845.png)

**Comment by foxes1998** [comment]
if you have root permission , it may work.

`su`
`export PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:$PATH`
`export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib`

then I tested minecraft:
![image](https://user-images.githubusercontent.com/58242212/86469510-226e6800-bd6c-11ea-9cb6-c1403ebeb845.png)

**Comment by 7Ragnarok7** [comment]
Try running it in a proot environment. 
```
proot -0
```

**Comment by foxes1998** [comment]
> if you have root permission , it may work(worked for me ).
> 
> `su`
> `export PATH=/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets:$PATH`
> `export LD_LIBRARY_PATH=/data/data/com.termux/files/usr/lib`
> 
> then I tested minecraft:
> ![image](https://user-images.githubusercontent.com/58242212/86469510-226e6800-bd6c-11ea-9cb6-c1403ebeb845.png)

you can use `tsu` pkg to instead of change env ( export PATH...)
just install it by:
`pkg install tsu`
 
also can use `sudo` if you installed `tsu`, just type `tsudo`

**Comment by ThiagaoPlusPlus** [comment]
Using tsu and running java as root worked for me too.
I have a Samsung i9100 with LineageOS 14.
