### ISSUE TITLE
Invalid system call

### ISSUE THREAD

**Issue by Kry9toN** [MasterDevX/Termux-Java#9]
![Screenshot_20190905-164502_Termux](https://user-images.githubusercontent.com/44697929/64331240-a2b52700-cffc-11e9-81a3-ab3e54ba1f48.png)

I'm on a Vince Android 9 device

**Comment by billysusanto** [comment]
i got the same message. anyone know whats the problem?

**Comment by Kry9toN** [comment]
The solution is to install ubuntu on termux then install open jdk 8

**Comment by javabird25** [comment]
Call `java` with proot:
```
proot java
```

**Comment by Kry9toN** [comment]
> Call `java` with proot:
> 
> ```
> proot java
> ```

Work well?

**Comment by javabird25** [comment]
> > Call `java` with proot:
> > ```
> > proot java
> > ```
> 
> Work well?

I tried termux-java for running [Apktool](https://ibotpeaches.github.io/Apktool) and it worked without any noticeable problems.

**Comment by Kry9toN** [comment]
> > > Call `java` with proot:
> > > ```
> > > proot java
> > > ```
> > 
> > 
> > Work well?
> 
> I tried termux-java for running [Apktool](https://ibotpeaches.github.io/Apktool) and it worked without any noticeable problems.

Which version are you on Android?

**Comment by javabird25** [comment]
> > > > Call `java` with proot:
> > > > ```
> > > > proot java
> > > > ```
> > > 
> > > 
> > > Work well?
> > 
> > 
> > I tried termux-java for running [Apktool](https://ibotpeaches.github.io/Apktool) and it worked without any noticeable problems.
> 
> Which version are you on Android?

9.0

**Comment by puddingepoch** [comment]
why cant fosstards do anything right
like, ever

**Comment by pitust** [comment]
The exact syscall failing is set_robust_list. Also happens to me on android 11 (pixel 3a; developer beta android;build rpb2.200611.009)
It happens due to seccomp policies i think.```
set_robust_list(0x79a1a4c0e0, 24)       = 522402971872
--- SIGSYS {si_signo=SIGSYS, si_code=SYS_SECCOMP, si_call_addr=0x79a1a03790, si_syscall=__NR_set_robust_list, si_arch=AUDIT_ARCH_AARCH64} ---
+++ killed by SIGSYS +++
Bad system call
````

**Comment by pitust** [comment]
Using proot worked

**Comment by pitust** [comment]
> why cant fosstards do anything right
> like, ever
Umm... Look up eternalblue. Pretty sure that was a big fuck up on MS's side. And spectre from intel. Closed source people also fyck up. And this is *literally* a cpu emulator in JavaScript.

**Comment by psujit775** [comment]
Facing the same problem.
Use proot
![IMG_20200815_003350](https://user-images.githubusercontent.com/50701338/90284124-11e2fe80-de8f-11ea-88d0-d93e93054105.jpg)

**Comment by romanin-rf** [comment]
Thank you!

**Comment by Kry9toN** [comment]
Now this issue done, use `proot` to call java in termux
